spring.application.name=ATSCIRCLE

# JWT Secret
jwt.secret=my-secret-key

# MongoDB Connection URI
# spring.data.mongodb.uri=mongodb+srv://ATSCircle:support%40ats@atscircle.unodk4k.mongodb.net/ATSCIRCLE?retryWrites=true&w=majority
spring.data.mongodb.uri=mongodb+srv://support_db_user:support%402026@cluster0.uvjkda4.mongodb.net/ATSCIRCLE?retryWrites=true&w=majority&authSource=admin
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.connectiontimeout=5000
# SMTP Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=support@clustrops.com
spring.mail.password=qyse pzuo tujv jetc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.security=DEBUG
logging.level.com.example.ATSCIRCLE.security=DEBUG

aws.s3.bucket= bucket-s3-atscircle
aws.s3.region=ap-south-1
aws.s3.access-key=AKIAW2H2Z6PW7F7EBRNI
aws.s3.secret-key=zaXDduraV1sFdXqx3gXjwfTCcNPil/Y92D/U/FH/


google.client.id=496274266752-k49l4suidqia8khf0b00ud3pmr618cbp.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:8080/api/oauth2/callback/google

microsoft.client.id=a28ca27b-5a09-47a7-8be4-3db899168905
microsoft.client.secret=01j8Q~g3oOHXMlengiQJEEoxI8Rrp8K5RA2Sgc7I
microsoft.redirect.uri=http://localhost:8080/api/oauth2/callback/microsoft
microsoft.tenant.id=a06f3cf2-ef16-46b2-a71d-1e2f4d14a516

# File upload size limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
